// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHNzgvg-Y3LXuwKe9f5mcHtuRD1-X4bU',
    appId: '1:1052272811460:web:832f616d2d5fd8061d9891',
    messagingSenderId: '1052272811460',
    projectId: 'multi-store-93b9a',
    authDomain: 'multi-store-93b9a.firebaseapp.com',
    storageBucket: 'multi-store-93b9a.appspot.com',
    measurementId: 'G-3TWS2YYPHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaShO964UIo29QUmqSdFGRk-0WlZL1zwc',
    appId: '1:1052272811460:android:4919758880d9f2b31d9891',
    messagingSenderId: '1052272811460',
    projectId: 'multi-store-93b9a',
    storageBucket: 'multi-store-93b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJCCr3qoirR3axsHEGvbk_b1rgDZHNYQ',
    appId: '1:1052272811460:ios:c38e7ca95773e8d81d9891',
    messagingSenderId: '1052272811460',
    projectId: 'multi-store-93b9a',
    storageBucket: 'multi-store-93b9a.appspot.com',
    iosClientId: '1052272811460-7517v4rv3hc3rcs1d9ol38s0p6ues5ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKJCCr3qoirR3axsHEGvbk_b1rgDZHNYQ',
    appId: '1:1052272811460:ios:c38e7ca95773e8d81d9891',
    messagingSenderId: '1052272811460',
    projectId: 'multi-store-93b9a',
    storageBucket: 'multi-store-93b9a.appspot.com',
    iosClientId: '1052272811460-7517v4rv3hc3rcs1d9ol38s0p6ues5ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStore',
  );
}
